import { StyleSheet } from '@react-pdf/renderer'

export const pdfStyles = StyleSheet.create({
  page: {
    paddingTop: 28,
    paddingBottom: 48,
    paddingHorizontal: 36,
    fontSize: 10,
    color: '#111',
    fontFamily: 'Inter Tight',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 20,
  },
  brandBlock: {
    flexDirection: 'row',
    alignItems: 'center',
    flexGrow: 1,
    flexShrink: 1,
    paddingRight: 20,
  },
  // text-fg-muted → --color-fg-muted (#a6a6a6)
  brandSubtitle: {
    width: 190,
    fontSize: 6,
    color: '#a6a6a6',
    lineHeight: 1.25,
    marginLeft: 6,
  },
  qrHeader: {
    width: 168,
    flexShrink: 0,
    alignItems: 'flex-end',
  },
  qrCaption: {
    width: '100%',
    fontSize: 7.5,
    color: '#868686', // text-fg-secondary
    marginBottom: 5,
    textAlign: 'right',
  },
  qrBlock: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  qrItem: {
    alignItems: 'center',
    width: 76,
    marginLeft: 12,
  },
  qrImage: { width: 72, height: 72 },
  qrLabel: {
    fontSize: 7.5,
    marginTop: 3,
    textAlign: 'center',
    color: '#868686', // text-fg-secondary
  },
  logo: { width: 78, height: 25 },
  h1: { fontSize: 16, fontWeight: 700, marginBottom: 8 },
  sectionTitle: {
    fontSize: 10,
    color: '#8a7a6a',
    marginTop: 12,
    marginBottom: 4,
  },
  text: { fontSize: 10, lineHeight: 1.4 },
  textBold: { fontSize: 10, lineHeight: 1.4, fontWeight: 700 },
  muted: { fontSize: 9, color: '#666', lineHeight: 1.3 },
  bold: { fontWeight: 700 },
  row: { flexDirection: 'row' },
  col: { flex: 1, paddingRight: 10 },
  colLast: { flex: 1, paddingLeft: 10 },
  methodsRow: { flexDirection: 'row', flexWrap: 'wrap' },
  methodCard: { width: '31%', marginBottom: 12, marginRight: '2%' },
  methodTitle: { fontSize: 10, fontWeight: 700, marginBottom: 4 },
  methodAge: { fontSize: 9, color: '#666', marginTop: 4 },
  methodImage: {
    width: '100%',
    height: 160,
    marginVertical: 6,
  },
  contraItem: { marginBottom: 8 },
  contraName: { fontSize: 10, fontWeight: 700, marginBottom: 2 },
  roleLabel: { fontSize: 9, color: '#666', marginTop: 6, marginBottom: 2 },
  storageLine: { fontSize: 10, lineHeight: 1.4, marginBottom: 2 },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 4,
  },
  statusIconBase: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginTop: 1,
    marginRight: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusIconDanger: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginTop: 1,
    marginRight: 6,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E11D48',
  },
  statusIconWarn: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginTop: 1,
    marginRight: 6,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F59E0B',
  },
  statusIconOk: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginTop: 1,
    marginRight: 6,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#16A34A',
  },
  statusIconText: { color: '#fff', fontSize: 7, fontWeight: 700 },
  divider: {
    marginTop: 16,
    marginBottom: 10,
    paddingVertical: 7,
    paddingHorizontal: 10,
    backgroundColor: '#e8e8e8',
    fontSize: 10,
    fontWeight: 700,
  },
  commentBox: {
    marginTop: 14,
    padding: 10,
    backgroundColor: '#f0f0f0',
  },
  commentTitle: {
    fontSize: 9,
    color: '#666',
    marginBottom: 6,
  },
  revisionDate: {
    marginTop: 8,
    fontSize: 9,
    color: '#666',
    textAlign: 'right',
  },
  footer: {
    position: 'absolute',
    bottom: 24,
    left: 0,
    right: 0,
    textAlign: 'center',
    fontSize: 9,
    color: '#666',
  },
})
