import { StyleSheet } from '@react-pdf/renderer'

export const pdfStyles = StyleSheet.create({
  page: {
    paddingTop: 40,
    paddingBottom: 48,
    paddingHorizontal: 40,
    fontSize: 10,
    color: '#111',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  brandBlock: { maxWidth: '55%' },
  brandTitle: { fontSize: 16, fontWeight: 700 },
  brandSubtitle: { fontSize: 8, color: '#666', marginTop: 4 },
  qrBlock: { flexDirection: 'row', gap: 12 },
  qrItem: { alignItems: 'center', width: 64 },
  qrImage: { width: 56, height: 56 },
  qrLabel: { fontSize: 7, marginTop: 4, textAlign: 'center' },
  h1: { fontSize: 14, fontWeight: 700, marginBottom: 8 },
  sectionTitle: { fontSize: 11, color: '#8a7a6a', marginTop: 12, marginBottom: 4 },
  text: { fontSize: 10, lineHeight: 1.4 },
  bold: { fontWeight: 700 },
  row: { flexDirection: 'row', gap: 16 },
  col: { flex: 1 },
  methodsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  methodCard: { width: '30%', marginBottom: 8 },
  methodImage: { width: '100%', height: 70, objectFit: 'cover', marginVertical: 4 },
  divider: {
    marginTop: 16,
    marginBottom: 8,
    paddingVertical: 6,
    paddingHorizontal: 8,
    backgroundColor: '#e8e8e8',
    fontSize: 10,
  },
  commentBox: {
    marginTop: 12,
    padding: 10,
    backgroundColor: '#f0f0f0',
  },
  footer: {
    position: 'absolute',
    bottom: 24,
    left: 0,
    right: 0,
    textAlign: 'center',
    fontSize: 9,
    color: '#666',
  },

  logo: { width: 116, height: 37, marginBottom: 6 },
  qrCaption: { fontSize: 8, color: '#666', marginBottom: 6, textAlign: 'right' },
})