import { StyleSheet } from '@react-pdf/renderer'

export const pdfStyles = StyleSheet.create({
  page: {
    paddingTop: 15,
    paddingBottom: 40,
    paddingHorizontal: 34,
    fontSize: 10,
    color: '#111',
    fontFamily: 'Inter Tight',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 5.3,
  },
  brandBlock: {
    flexDirection: 'row',
    alignItems: 'center',
    flexGrow: 1,
    flexShrink: 1,
    paddingRight: 20,
  },
  brandSubtitle: {
    width: 190,
    fontSize: 6,
    color: '#a6a6a6',
    lineHeight: 1.25,
    marginLeft: 6,
  },
  qrHeader: {
    width: 168,
    flexShrink: 0,
    alignItems: 'flex-end',
  },
  qrCaption: {
    width: '100%',
    fontSize: 7.5,
    color: '#868686',
    marginBottom: 5,
    textAlign: 'right',
  },
  qrBlock: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  qrItem: {
    alignItems: 'center',
    width: 76,
    marginLeft: 12,
  },
  qrImage: { width: 72, height: 72 },
  qrLabel: {
    fontSize: 7.5,
    marginTop: 3,
    textAlign: 'center',
    color: '#868686',
  },
  logo: { width: 78, height: 25 },
  nameBlock: {
    marginBottom: 0,
  },
  h1: {
    fontSize: 11.5,
    fontWeight: 600,
    lineHeight: 1,
    marginBottom: 9.6,
  },
  officialNameLabelWrap: {
    marginBottom: 7.2,
  },
  officialName: {
    fontSize: 11.5,
    fontWeight: 600,
    lineHeight: 1.15,
    marginBottom: 7.2,
  },

  importantNote: {
    fontSize: 6.7,
    fontWeight: 400,
    fontStyle: 'italic',
    lineHeight: 1,
    color: '#868686',
    marginTop: 7.2,
  },
  twoColRow: {
    flexDirection: 'row',
    marginTop: 24,
  },
  twoColLeft: {
    flex: 1,
    paddingRight: 31.2,
  },
  twoColRight: {
    flex: 1,
    paddingLeft: 31.2,
  },
  infectionsValue: {
    fontSize: 11.5,
    fontWeight: 600,
    lineHeight: 1,
    marginTop: 7.2,
  },
  ageValue: {
    fontSize: 11.5,
    fontWeight: 600,
    lineHeight: 1,
    marginTop: 7.9,
  },
  sectionHeading: {
    fontSize: 10,
    fontWeight: 600,
    lineHeight: 1,
    color: '#737373',
  },
  methodsSection: {
    marginTop: 24,
  },
  contraSection: {
    marginTop: 24,
  },
  contraGroupLabel: {
    fontSize: 7.7,
    fontWeight: 400,
    lineHeight: 1.3,
    color: '#9A9A9A',
    marginTop: 7.2,
  },
  methodsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 7.2,
  },
  // 3 cards/row in ~527pt content: 127*3 + 70*2 = 521
  methodCard: {
    width: 127,
    marginRight: 70,
    marginBottom: 19.2,
    alignItems: 'flex-start',
  },
  methodCardLast: {
    width: 127,
    marginRight: 0,
    marginBottom: 19.2,
    alignItems: 'flex-start',
  },
  methodTitle: {
    width: 127,
    minHeight: 27.8,
    fontSize: 11.5,
    fontWeight: 600,
    lineHeight: 1,
    marginBottom: 5.5,
  },
  methodImage: {
    width: 100,
    height: 100,
  },
  methodAge: {
    marginTop: 7.2,
    fontSize: 7.7,
    fontWeight: 400,
    lineHeight: 1.3,
    color: '#868686',
  },
  methodsNote: {
    fontSize: 6.7,
    fontWeight: 400,
    fontStyle: 'italic',
    lineHeight: 1,
    color: '#868686',
    marginTop: 16.8,
  },
  contraName: {
    fontSize: 11.5,
    fontWeight: 600,
    lineHeight: 1.3,
    marginTop: 4.8,
  },
  infoSection: {
    marginTop: 24,
  },
  infoRow: {
    flexDirection: 'row',
  },
  infoColLeft: {
    width: 160.8,
    flexShrink: 0,
  },
  infoColRight: {
    width: 328.1,
    flexShrink: 0,
    marginLeft: 39.1,
  },
  infoBlock: {
    marginTop: 0,
  },
  infoBlockSpaced: {
    marginTop: 24,
  },
  infoBlockHeading: {
    fontSize: 10,
    fontWeight: 600,
    lineHeight: 1,
    color: '#737373',
    marginBottom: 7.2,
  },
  roleLabel: {
    fontSize: 7.7,
    fontWeight: 400,
    lineHeight: 1.3,
    color: '#9A9A9A',
    marginTop: 7.2,
  },
  infoValue: {
    fontSize: 11.5,
    fontWeight: 600,
    lineHeight: 1.3,
    marginTop: 4.8,
    color: '#323335',
  },
  storageLine: {
    fontSize: 11.5,
    fontWeight: 600,
    lineHeight: 1.3,
    color: '#323335',
    marginTop: 0,
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: 4.8,
  },
  statusIconBase: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginTop: 2,
    marginRight: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusIconDanger: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginTop: 2,
    marginRight: 6,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E11D48',
  },
  statusIconWarn: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginTop: 2,
    marginRight: 6,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F59E0B',
  },
  statusIconOk: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginTop: 2,
    marginRight: 6,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#16A34A',
  },
  statusIconText: { color: '#fff', fontSize: 7, fontWeight: 700 },
  statusValueWrap: {
    flex: 1,
  },
  statusValue: {
    fontSize: 11.5,
    fontWeight: 600,
    lineHeight: 1.3,
  },
  row: { flexDirection: 'row' },
  col: { flex: 1, paddingRight: 10 },
  colLast: { flex: 1, paddingLeft: 10 },
  sectionTitle: {
    marginTop: 24,
    fontSize: 10.1,
    fontWeight: 600,
    lineHeight: 1,
    color: '#737373',
  },
  text: {
    fontSize: 11.5,
    fontWeight: 600,
    lineHeight: 1.3,
    color: '#323335',
  },
  muted: { fontSize: 9, color: '#666', lineHeight: 1.3 },
  bold: { fontWeight: 700 },
  divider: {
    marginTop: 24,
    height: 24,
    paddingHorizontal: 10,
    backgroundColor: '#D9D9D9',
    justifyContent: 'center',
  },
  dividerText: {
    fontSize: 10.1,
    fontWeight: 600,
    lineHeight: 1,
    color: '#141414',
  },
  commentBox: {
    marginTop: 24,
    padding: 10,
    backgroundColor: '#F3F3F3',
  },
  commentTitle: {
    fontSize: 10.1,
    fontWeight: 600,
    lineHeight: 1,
    color: '#737373',
    marginBottom: 6,
  },
  commentBody: {
    fontSize: 11.5,
    fontWeight: 600,
    lineHeight: 1.3,
    color: '#323335',
  },
  revisionDate: {
    marginTop: 24,
    fontSize: 10.1,
    fontWeight: 600,
    lineHeight: 1,
    color: '#737373',
    textAlign: 'right',
  },
  footer: {
    position: 'absolute',
    bottom: 24,
    left: 0,
    right: 0,
    textAlign: 'center',
    fontSize: 9,
    color: '#666',
  },
})
