export {
  BREAKPOINT_DESKTOP_MIN_PX as SUMMARY_SIDEBAR_DESKTOP_MIN_PX,
  BREAKPOINT_SUMMARY_WIDE_MIN_PX as SUMMARY_SIDEBAR_WIDE_MIN_PX,
  SUMMARY_SIDEBAR_WIDTH_COMPACT_PX,
  SUMMARY_SIDEBAR_WIDTH_WIDE_PX,
} from '@/shared/config/breakpoints'
