import type { Contraindication, Infection, Ingredient, Vaccine } from '@/shared/types/api'

export const MOCK_VACCINES: Vaccine[] = [
  {
    id: 1,
    name: 'Пентаксим',
    infections: ['Дифтерия', 'Столбняк', 'Коклюш', 'Полиомиелит', 'Гемофильная инфекция'],
    administration_method: 'Внутримышечно',
    min_age_months: 2,
    max_age_months: null,
    allowed_during_pregnancy: false,
    popularity: 95,
  },
  {
    id: 2,
    name: 'Инфанрикс Гекса',
    infections: ['Дифтерия', 'Столбняк', 'Коклюш', 'Гепатит B', 'Полиомиелит', 'Хиб'],
    administration_method: 'Внутримышечно',
    min_age_months: 2,
    max_age_months: null,
    allowed_during_pregnancy: false,
    popularity: 90,
  },
  {
    id: 3,
    name: 'Приорикс',
    infections: ['Корь', 'Краснуха', 'Паротит'],
    administration_method: 'Подкожно',
    min_age_months: 12,
    max_age_months: null,
    allowed_during_pregnancy: false,
    popularity: 88,
  },
  {
    id: 4,
    name: 'Варилрикс',
    infections: ['Ветряная оспа'],
    administration_method: 'Подкожно',
    min_age_months: 12,
    max_age_months: null,
    allowed_during_pregnancy: false,
    popularity: 75,
  },
  {
    id: 5,
    name: 'Гардасил',
    infections: ['Вирус папилломы человека'],
    administration_method: 'Внутримышечно',
    min_age_months: 108,
    max_age_months: 540,
    allowed_during_pregnancy: false,
    popularity: 72,
  },
  {
    id: 6,
    name: 'Энджерикс Б',
    infections: ['Гепатит B'],
    administration_method: 'Внутримышечно',
    min_age_months: 0,
    max_age_months: null,
    allowed_during_pregnancy: true,
    popularity: 70,
  },
  {
    id: 7,
    name: 'Ультрикс',
    infections: ['Грипп'],
    administration_method: 'Внутримышечно',
    min_age_months: 6,
    max_age_months: null,
    allowed_during_pregnancy: true,
    popularity: 65,
  },
  {
    id: 8,
    name: 'Превенар 13',
    infections: ['Пневмококковая инфекция'],
    administration_method: 'Внутримышечно',
    min_age_months: 2,
    max_age_months: null,
    allowed_during_pregnancy: false,
    popularity: 60,
  },
]

export const MOCK_INFECTIONS: Infection[] = [
  { id: 1, name: 'Дифтерия', category: 'national_calendar', popularity: 90 },
  { id: 2, name: 'Столбняк', category: 'national_calendar', popularity: 88 },
  { id: 3, name: 'Коклюш', category: 'national_calendar', popularity: 85 },
  { id: 4, name: 'Полиомиелит', category: 'national_calendar', popularity: 83 },
  { id: 5, name: 'Корь', category: 'national_calendar', popularity: 80 },
  { id: 6, name: 'Краснуха', category: 'national_calendar', popularity: 78 },
  { id: 7, name: 'Паротит', category: 'national_calendar', popularity: 76 },
  { id: 8, name: 'Гепатит B', category: 'national_calendar', popularity: 74 },
  { id: 9, name: 'Ветряная оспа', category: 'extended', popularity: 72 },
  { id: 10, name: 'Грипп', category: 'extended', popularity: 70 },
]

export const MOCK_INGREDIENTS: Ingredient[] = [
  { id: 1, name: 'Алюминия гидроксид', type: 'Адъювант', popularity: 95 },
  { id: 2, name: 'Тиомерсал', type: 'Консервант', popularity: 80 },
  { id: 3, name: 'Формальдегид', type: 'Инактиватор', popularity: 75 },
  { id: 4, name: 'Полисорбат 80', type: 'Стабилизатор', popularity: 70 },
  { id: 5, name: 'Дрожжевой белок', type: 'Субстрат', popularity: 65 },
  { id: 6, name: 'Неомицин', type: 'Антибиотик', popularity: 60 },
  { id: 7, name: 'Желатин', type: 'Стабилизатор', popularity: 55 },
  { id: 8, name: 'Яичный белок', type: 'Субстрат', popularity: 50 },
]

export const MOCK_CONTRAINDICATIONS: Contraindication[] = [
  { id: 1, name: 'Аллергия на компоненты вакцины', category: 'Абсолютные', popularity: 95 },
  { id: 2, name: 'Анафилактическая реакция на предыдущую дозу', category: 'Абсолютные', popularity: 90 },
  { id: 3, name: 'Острое заболевание с температурой', category: 'Временные', popularity: 85 },
  { id: 4, name: 'Беременность', category: 'Относительные', popularity: 80 },
  { id: 5, name: 'Иммунодефицитные состояния', category: 'Абсолютные', popularity: 75 },
  { id: 6, name: 'Обострение хронического заболевания', category: 'Временные', popularity: 70 },
  { id: 7, name: 'Недоношенность (менее 28 недель)', category: 'Относительные', popularity: 65 },
  { id: 8, name: 'Аллергия на яичный белок', category: 'Относительные', popularity: 60 },
]
