name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-build:
    name: build NextJS container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Build Docker image
        run: docker build --pull --tag datavac-frontend:${{ github.sha }} .
